<?php
	include 'HolDB.class.php';
	$hol = new HolDB;
	$errMsg = ""; //сообщение об ошибке
	$resCurDate = "";	  //результат
	if ($_SERVER['REQUEST_METHOD'] == "POST"){
		include "getResult.inc.php";
		include "save_h.inc.php";		
	}
	if (isset ($_GET["del"]))
		include "delete_h.inc.php";	
?>
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8">
   <title>Календарь праздников</title>
   <script src="./js/jquery.js" type="text/javascript"></script>   
   <script src="./js/jquery-ui.min.js" type="text/javascript"></script>   
   <script src="./js/datepicker-ru.js" type="text/javascript"></script>   
   <link href="./css/jquery-ui.css" rel="stylesheet">
</head>
 <body>
	<h1>Проверь выходные</h1>
    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
    <label for="datepicker">Выберите дату: </legend>
    <input type="text" name="calendar" id="datepicker">
    <input type="submit" value="Проверить">
    </form>
    <script>
	$(function(){
		$.datepicker.setDefaults(
			$.extend($.datepicker.regional["ru"])
		);
		$("#datepicker").datepicker({
			changeMonth: true,
			changeYear: true,
			dateFormat: "dd.mm.yy"
		});
	});
    </script>
	<?php
		if ($errMsg) echo "<h3>$errMsg</h3>";
		else echo "<h2>$resCurDate</h2>";
	?>
	<h3>Добавление праздника</h3>
	<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
    <fieldset>
		<legend>Введи день праздника</legend>
		<div id="firstData">
			<label for="day">Число месяца: </legend>
			<input type="number" name="day" id="day" min="1" max="31" disabled onFocus="this.form.prodolzh.disabled=0; this.form.dweek.disabled=1;
			this.form.week.disabled=1;">
			<label for="month">Месяц: </legend>
			<select name="month" id="month" required onFocus="this.form.submit.disabled=0; this.form.day.disabled=0; this.form.dweek.disabled=0; this.form.week.disabled=0;" >
				<option selected value=0>Выберите месяц</option>
				<option value=1>Январь</option>
				<option value=2>Февраль</option>
				<option value=3>Март</option>
				<option value=4>Апрель</option>
				<option value=5>Май</option>
				<option value=6>Июнь</option>
				<option value=7>Июль</option>
				<option value=8>Август</option>
				<option value=9>Сентябрь</option>
				<option value=10>Октябрь</option>
				<option value=11>Ноябрь</option>
				<option value=12>Декабрь</option>
			</select>
			<label for="prodolzh">Дней: </legend>
			<input type="number" name="prodolzh" id="prodolzh" min="1" max="30" disabled>
		</div>
		<div id="secondData">
			<label for="dweek">День недели: </legend>
			<select name="dweek" id="dweek" disabled onFocus="this.form.prodolzh.disabled=0;
			this.form.day.disabled=1;">
				<option selected value=0>Выберите день недели</option>
				<option value=1>Понедельник</option>
				<option value=2>Вторник</option>
				<option value=3>Среда</option>
				<option value=4>Четверг</option>
				<option value=5>Пятница</option>
				<option value=6>Суббота</option>
				<option value=7>Воскресенье</option>
			</select>
			<label for="week">Неделя: </legend>
			<select name="week" id="week" value="" disabled onFocus="this.form.prodolzh.disabled=0;
			this.form.day.disabled=1;">
				<option selected value=0>Выберите неделю</option>
				<option value=1>первая</option>
				<option value=2>вторая</option>
				<option value=3>третяя</option>
				<option value=4>четвёртая</option>
				<option value=5>последняя</option>
			</select>
		</div>
		<input type="submit" id="submit" value="Добавить" disabled>
	</fieldset>
    </form>
	<?php
		include "get_h.inc.php";
	?>
 </body>
</html>